apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.fullName }}
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
        app: {{ .Values.selectorLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullName}}
        type: hStreamNode
        hsServiceName: {{ .Values.fullName }}
    spec:
      containers:
        - name: {{ .Values.containers.hs_adapter.name}}
          image: {{ .Values.containers.hs_adapter.image}}
          imagePullPolicy: {{ .Values.containers.hs_adapter.pullPolicy}}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: ipfs-cluster.Port
              value: "9094"
            - name: ipfs-cluster.Host
              value: "ipfs-cluster-node.default.svc.cluster.local"
            - name: postgres.Host
              value: "solenopsys-ds-postgres.default.svc.cluster.local"
            - name: postgres.Port
              value: "5432"
            - name: postgres.Password
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pg-password
                  optional: false
            - name: postgres.User
              value: postgres
            - name: api.Port
              value: "{{ .Values.service.port }}"
      terminationGracePeriodSeconds: 60