apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name:  platform-ms-pinning
  namespace: kube-system
spec:
  chart:  platform-ms-pinning
  targetNamespace: default
  version: 0.1.2
  repo: https://helm.solenopsys.org
  helmVersion: v3